/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ophelia_net;

import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
/**
 *
 * @author LENOVO
 */
public class P11_1_1chooseFingerEvi extends javax.swing.JPanel {
    public static boolean[] checked = {false,false,false,false,false,false,false};
    // index : 
    //   0  : wine   , 1 : spoon , 2 : chocolate , 3 : liquor , 4 : water , 5 : plate ,  6 : pot
    private CardLayout cd;
    private JPanel mainPanel;
    public static final String ADDRESS ="fingerSelected";
    public static String BACKPAGE;
    public P11_1_1chooseFingerEvi(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        cd = (CardLayout) mainPanel.getLayout();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nextBT = new javax.swing.JButton();
        liquorBT = new javax.swing.JButton();
        plateBT = new javax.swing.JButton();
        spoonBT = new javax.swing.JButton();
        potBT = new javax.swing.JButton();
        waterBT = new javax.swing.JButton();
        boxBT = new javax.swing.JButton();
        coin = new javax.swing.JLabel();
        coinLB = new javax.swing.JLabel();
        toolLB = new javax.swing.JLabel();
        fileLB1 = new javax.swing.JLabel();
        boxLB = new javax.swing.JLabel();
        plateLB = new javax.swing.JLabel();
        medbottleLB = new javax.swing.JLabel();
        water = new javax.swing.JLabel();
        liquorLB = new javax.swing.JLabel();
        spoonLB = new javax.swing.JLabel();
        wineBT1 = new javax.swing.JButton();
        wineLB1 = new javax.swing.JLabel();
        backBT = new javax.swing.JButton();
        navybg = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 700));
        setLayout(null);

        nextBT.setBackground(new java.awt.Color(242, 242, 242));
        nextBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        nextBT.setText("Next>");
        nextBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        nextBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextBTActionPerformed(evt);
            }
        });
        add(nextBT);
        nextBT.setBounds(1000, 620, 110, 40);

        liquorBT.setBackground(new java.awt.Color(242, 242, 242));
        liquorBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        liquorBT.setText("CHOOSE");
        liquorBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        liquorBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                liquorBTActionPerformed(evt);
            }
        });
        add(liquorBT);
        liquorBT.setBounds(100, 500, 110, 40);

        plateBT.setBackground(new java.awt.Color(242, 242, 242));
        plateBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        plateBT.setText("CHOOSE");
        plateBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        plateBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                plateBTActionPerformed(evt);
            }
        });
        add(plateBT);
        plateBT.setBounds(700, 500, 110, 40);

        spoonBT.setBackground(new java.awt.Color(242, 242, 242));
        spoonBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        spoonBT.setText("CHOOSE");
        spoonBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        spoonBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                spoonBTActionPerformed(evt);
            }
        });
        add(spoonBT);
        spoonBT.setBounds(540, 240, 110, 40);

        potBT.setBackground(new java.awt.Color(242, 242, 242));
        potBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        potBT.setText("CHOOSE");
        potBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        potBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potBTActionPerformed(evt);
            }
        });
        add(potBT);
        potBT.setBounds(1000, 500, 110, 40);

        waterBT.setBackground(new java.awt.Color(242, 242, 242));
        waterBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        waterBT.setText("CHOOSE");
        waterBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        waterBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                waterBTActionPerformed(evt);
            }
        });
        add(waterBT);
        waterBT.setBounds(370, 500, 110, 40);

        boxBT.setBackground(new java.awt.Color(242, 242, 242));
        boxBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        boxBT.setText("CHOOSE");
        boxBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        boxBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxBTActionPerformed(evt);
            }
        });
        add(boxBT);
        boxBT.setBounds(860, 240, 110, 40);

        coin.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        coin.setFont(new java.awt.Font("Leelawadee", 1, 20)); // NOI18N
        coin.setText("   3");
        coin.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        coin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        add(coin);
        coin.setBounds(1110, 40, 50, 20);

        coinLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/coin.png"))); // NOI18N
        add(coinLB);
        coinLB.setBounds(1100, 20, 63, 63);

        toolLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/hint.png"))); // NOI18N
        toolLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toolLBMouseClicked(evt);
            }
        });
        add(toolLB);
        toolLB.setBounds(980, 10, 70, 80);

        fileLB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/filebg.png"))); // NOI18N
        fileLB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileLB1MouseClicked(evt);
            }
        });
        add(fileLB1);
        fileLB1.setBounds(1040, 20, 70, 70);

        boxLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/box.png"))); // NOI18N
        add(boxLB);
        boxLB.setBounds(800, 70, 213, 213);

        plateLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/plate.png"))); // NOI18N
        add(plateLB);
        plateLB.setBounds(650, 300, 200, 200);
        plateLB.getAccessibleContext().setAccessibleDescription("");

        medbottleLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/medicinebottle.png"))); // NOI18N
        add(medbottleLB);
        medbottleLB.setBounds(960, 300, 200, 200);

        water.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/water.png"))); // NOI18N
        add(water);
        water.setBounds(330, 330, 170, 150);

        liquorLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/liquor.png"))); // NOI18N
        add(liquorLB);
        liquorLB.setBounds(50, 300, 200, 200);

        spoonLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/spoon.png"))); // NOI18N
        add(spoonLB);
        spoonLB.setBounds(480, 70, 210, 200);

        wineBT1.setBackground(new java.awt.Color(242, 242, 242));
        wineBT1.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        wineBT1.setText("CHOOSE");
        wineBT1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        wineBT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                wineBT1ActionPerformed(evt);
            }
        });
        add(wineBT1);
        wineBT1.setBounds(210, 240, 110, 40);

        wineLB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/wine.png"))); // NOI18N
        add(wineLB1);
        wineLB1.setBounds(170, 40, 200, 200);

        backBT.setBackground(new java.awt.Color(242, 242, 242));
        backBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        backBT.setText("<BACK");
        backBT.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, new java.awt.Color(255, 255, 255), new java.awt.Color(255, 255, 255), new java.awt.Color(0, 0, 0), new java.awt.Color(0, 0, 0)));
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });
        backBT.setVisible(false);
        backBT.setEnabled(false);
        add(backBT);
        backBT.setBounds(80, 620, 110, 40);

        navybg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/navybg.jpg"))); // NOI18N
        navybg.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        add(navybg);
        navybg.setBounds(0, 0, 1200, 700);
    }// </editor-fold>//GEN-END:initComponents

    private void toolLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolLBMouseClicked
        // TODO add your handling code here:
        P_Hint_page.backPage=ADDRESS;
        cd.show(mainPanel,"toolPage");
    }//GEN-LAST:event_toolLBMouseClicked

    private void fileLB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileLB1MouseClicked
        // TODO add your handling code here:
        P_Menu_icon.backPage=ADDRESS;
        cd.show(mainPanel,"menuBtn");
    }//GEN-LAST:event_fileLB1MouseClicked

    private void nextBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextBTActionPerformed
        // TODO add your handling code here:
        if(checkVisit()){
            testimonyPageLookBack.fingerSelBtn.setEnabled(true);
            nextBT.setEnabled(false);
            nextBT.setVisible(false);
            for(int i = 0 ; i<checked.length ; i++){
                checked[i] = false;  
                System.out.print("TSET : "+i);
            }
            
            backBT.setVisible(true);
            backBT.setEnabled(true);
            
            setBackbtn(P11_1_Boxfingerprint_2.backBt,P11_1_Boxfingerprint_2.fileLB1,P11_1_Boxfingerprint_2.toolLB,P11_1_Boxfingerprint_2.coin,P11_1_Boxfingerprint_2.coinLB);
            setBackbtn(P11_1_Boxfingerprint_1.backBt,P11_1_Boxfingerprint_1.fileLB1,P11_1_Boxfingerprint_1.toolLB,P11_1_Boxfingerprint_1.coin,P11_1_Boxfingerprint_1.coinLB);
            removeConfirmbtn(P11_1_Boxfingerprint_2.confirmBT);
            
            setBackbtn(P11_1_Liquorfingerprint.backBt,P11_1_Liquorfingerprint.fileLB1,P11_1_Liquorfingerprint.toolLB,P11_1_Liquorfingerprint.coin,P11_1_Liquorfingerprint.coinLB);
            removeConfirmbtn(P11_1_Liquorfingerprint.confirmBT);
            
            setBackbtn(P11_1_MedfingerprintPot_1.backBt,P11_1_MedfingerprintPot_1.fileLB1,P11_1_MedfingerprintPot_1.toolLB,P11_1_MedfingerprintPot_1.coin,P11_1_MedfingerprintPot_1.coinLB);
            setBackbtn(P11_1_MedfingerprintPot_2.backBt,P11_1_MedfingerprintPot_2.fileLB1,P11_1_MedfingerprintPot_2.toolLB,P11_1_MedfingerprintPot_2.coin,P11_1_MedfingerprintPot_2.coinLB);
            removeConfirmbtn(P11_1_MedfingerprintPot_2.confirmBT);
            
            setBackbtn(P11_1_PlatefingerprintPlate.backBt,P11_1_PlatefingerprintPlate.fileLB1,P11_1_PlatefingerprintPlate.toolLB,P11_1_PlatefingerprintPlate.coin,P11_1_PlatefingerprintPlate.coinLB); 
            removeConfirmbtn(P11_1_PlatefingerprintPlate.confirmBT);
            
            setBackbtn(P11_1_Spoonfingerprint_1.backBt,P11_1_Spoonfingerprint_1.fileLB1,P11_1_Spoonfingerprint_1.toolLB,P11_1_Spoonfingerprint_1.coin,P11_1_Spoonfingerprint_1.coinLB);
            setBackbtn(P11_1_Spoonfingerprint_2.backBt,P11_1_Spoonfingerprint_2.fileLB1,P11_1_Spoonfingerprint_2.toolLB,P11_1_Spoonfingerprint_2.coin,P11_1_Spoonfingerprint_2.coinLB);
            removeConfirmbtn(P11_1_Spoonfingerprint_2.confirmBT);
            
            setBackbtn(P11_1_Waterfingerprint.backBt,P11_1_Waterfingerprint.fileLB1,P11_1_Waterfingerprint.toolLB,P11_1_Waterfingerprint.coin,P11_1_Waterfingerprint.coinLB);
            removeConfirmbtn(P11_1_Waterfingerprint.confirmBT);
            
            setBackbtn(P11_1_Winefingerprint.backBt,P11_1_Winefingerprint.fileLB1,P11_1_Winefingerprint.toolLB,P11_1_Winefingerprint.coin,P11_1_Winefingerprint.coinLB);
            removeConfirmbtn(P11_1_Winefingerprint.confirmBT);

            cd.show(mainPanel,"selectWaytoCheck");
            
            setBackbtn(null,fileLB1,toolLB,coin,coinLB);

        }else{
            JOptionPane.showMessageDialog(this, "You have to check all object", "check", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_nextBTActionPerformed
    private void setBackbtn(JButton b,JLabel l1,JLabel l2,JLabel l3,JLabel l4){
        if(b!=null){
            b.setVisible(true);
            b.setEnabled(true);
        }
        try{
            l1.setVisible(false);
            l1.setEnabled(false);
        }catch(Exception e ){System.out.println(e);}
        try{
            l2.setVisible(false);
            l2.setEnabled(false);
        }catch(Exception e){System.out.println(e);}
        try{
            l3.setVisible(false);
            l3.setEnabled(false);
        }catch(Exception e){System.out.println(e);}
        try{
            l4.setVisible(false);
            l4.setEnabled(false);
        }catch(Exception e){System.out.println(e);}
        
    }
    private void removeConfirmbtn(JButton b){
        b.setVisible(false);
        b.setEnabled(false);
    }
    private void wineBT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_wineBT1ActionPerformed
        if(!checked[0]){
            cd.show(mainPanel,"Wine");
            wineBT1.setBackground(Color.green);
            wineBT1.setText("Checked");
        }
        else 
            JOptionPane.showMessageDialog(this, "You have already checked this object", "checked", JOptionPane.INFORMATION_MESSAGE);
        
            
    }//GEN-LAST:event_wineBT1ActionPerformed

    private void spoonBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_spoonBTActionPerformed
        if(!checked[1]){
            cd.show(mainPanel,"Spoon1");
            spoonBT.setBackground(Color.green);
            spoonBT.setText("Checked");
        }
        else 
            JOptionPane.showMessageDialog(this, "You have already checked this object", "checked", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_spoonBTActionPerformed

    private void boxBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxBTActionPerformed
        if(!checked[2]){
            cd.show(mainPanel,"BOX1");
            boxBT.setBackground(Color.green);
            boxBT.setText("Checked");
        }
        else JOptionPane.showMessageDialog(this, "You have already checked this object", "checked", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_boxBTActionPerformed

    private void liquorBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_liquorBTActionPerformed
        if(!checked[3]){
            cd.show(mainPanel,"Liquor");
            liquorBT.setBackground(Color.green);
            liquorBT.setText("Checked");
        }
        else JOptionPane.showMessageDialog(this, "You have already checked this object", "checked", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_liquorBTActionPerformed

    private void waterBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_waterBTActionPerformed
        if(!checked[4]){
            cd.show(mainPanel,"Water");
            waterBT.setBackground(Color.green);
            waterBT.setText("Checked");
        }
            
        else JOptionPane.showMessageDialog(this, "You have already checked this object", "checked", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_waterBTActionPerformed

    private void plateBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_plateBTActionPerformed
        if(!checked[5]){
            cd.show(mainPanel,"Plate");
            plateBT.setBackground(Color.green);
            plateBT.setText("Checked");
        }
        else JOptionPane.showMessageDialog(this, "You have already checked this object", "checked", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_plateBTActionPerformed

    private void potBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potBTActionPerformed
        if(!checked[6]){
            cd.show(mainPanel,"MedF1");
            potBT.setBackground(Color.green);
            potBT.setText("Checked");
        }
        else JOptionPane.showMessageDialog(this, "You have already checked this object", "checked", JOptionPane.INFORMATION_MESSAGE);
    
    }//GEN-LAST:event_potBTActionPerformed

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
        cd.show(mainPanel,"testimonyPageLookBack");
    }//GEN-LAST:event_backBTActionPerformed
    
    //check that every evidence is done
    private boolean checkVisit(){
        for(boolean  i : checked){
            if(i==false){
                return false;
            }
        }
        return true;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBT;
    private javax.swing.JButton boxBT;
    private javax.swing.JLabel boxLB;
    static javax.swing.JLabel coin;
    static javax.swing.JLabel coinLB;
    static javax.swing.JLabel fileLB1;
    private javax.swing.JButton liquorBT;
    private javax.swing.JLabel liquorLB;
    private javax.swing.JLabel medbottleLB;
    private javax.swing.JLabel navybg;
    private javax.swing.JButton nextBT;
    private javax.swing.JButton plateBT;
    private javax.swing.JLabel plateLB;
    private javax.swing.JButton potBT;
    private javax.swing.JButton spoonBT;
    private javax.swing.JLabel spoonLB;
    static javax.swing.JLabel toolLB;
    private javax.swing.JLabel water;
    private javax.swing.JButton waterBT;
    private javax.swing.JButton wineBT1;
    private javax.swing.JLabel wineLB1;
    // End of variables declaration//GEN-END:variables
}
