/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ophelia_net;

import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Chotika
 */
public class P4_4Instruction extends javax.swing.JPanel {
    private CardLayout cd;
    private JPanel mainPanel;
    private static final String ADDRESS="instruction";
    /**
     * Creates new form StartPage1
     */
    public P4_4Instruction(JPanel mainPanel) {
        this.mainPanel = mainPanel;
        cd = (CardLayout) mainPanel.getLayout();
        initComponents();
    }
//    public static void main(String[] args) {
////        try{
////            UIManager.setLookAndFeel( new FlatMacLightLaf());
////        }
////        catch(Exception e){
////            System.err.println( "Failed to initialize LaF" );
////        }
//        JFrame Instruct_Frame = new JFrame();
//        Instruct_Frame.setContentPane(new P4_4Instruction());
//        
//        Instruct_Frame.setVisible(true);
//        Instruct_Frame.setSize(1200, 700);
//        Instruct_Frame.setLocationRelativeTo(null);
//        Instruct_Frame.setResizable(false);
//        Instruct_Frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        backBT = new javax.swing.JButton();
        jLabel_coin = new javax.swing.JLabel();
        jLabel_file = new javax.swing.JLabel();
        jLabel_tool = new javax.swing.JLabel();
        toolLB = new javax.swing.JLabel();
        fileLB1 = new javax.swing.JLabel();
        coin = new javax.swing.JLabel();
        coinLB = new javax.swing.JLabel();
        nextBT = new javax.swing.JButton();
        inst_2 = new javax.swing.JLabel();
        inst_1 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(1200, 700));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setBackground(new java.awt.Color(47, 46, 62));
        jPanel1.setPreferredSize(new java.awt.Dimension(1185, 1300));
        jPanel1.setLayout(null);

        backBT.setBackground(new java.awt.Color(242, 242, 242));
        backBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        backBT.setText("<Back");
        backBT.setToolTipText("");
        backBT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 5, 4, 0, new java.awt.Color(174, 0, 0)));
        backBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backBTMouseClicked(evt);
            }
        });
        backBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBTActionPerformed(evt);
            }
        });
        jPanel1.add(backBT);
        backBT.setBounds(110, 1210, 100, 40);

        jLabel_coin.setFont(new java.awt.Font("TH Sarabun New", 1, 20)); // NOI18N
        jLabel_coin.setForeground(new java.awt.Color(255, 202, 40));
        jLabel_coin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_coin.setText("เหรียญ");
        jPanel1.add(jLabel_coin);
        jLabel_coin.setBounds(1080, 60, 60, 25);

        jLabel_file.setFont(new java.awt.Font("TH Sarabun New", 1, 20)); // NOI18N
        jLabel_file.setForeground(new java.awt.Color(201, 156, 99));
        jLabel_file.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_file.setText("บันทึกคดี");
        jPanel1.add(jLabel_file);
        jLabel_file.setBounds(1010, 60, 70, 25);

        jLabel_tool.setFont(new java.awt.Font("TH Sarabun New", 1, 20)); // NOI18N
        jLabel_tool.setForeground(new java.awt.Color(117, 180, 129));
        jLabel_tool.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_tool.setText("คู่มือ");
        jPanel1.add(jLabel_tool);
        jLabel_tool.setBounds(950, 60, 60, 25);

        toolLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        toolLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/hint.png"))); // NOI18N
        toolLB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolLB.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                toolLBMouseClicked(evt);
            }
        });
        jPanel1.add(toolLB);
        toolLB.setBounds(950, 10, 60, 50);

        fileLB1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        fileLB1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/filebg.png"))); // NOI18N
        fileLB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                fileLB1MouseClicked(evt);
            }
        });
        jPanel1.add(fileLB1);
        fileLB1.setBounds(1010, 10, 80, 50);

        coin.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));
        coin.setFont(new java.awt.Font("Leelawadee", 1, 20)); // NOI18N
        coin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coin.setText(" 3 ");
        coin.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.add(coin);
        coin.setBounds(1090, 0, 40, 60);

        coinLB.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        coinLB.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/coin.png"))); // NOI18N
        coinLB.setAlignmentY(0.0F);
        coinLB.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel1.add(coinLB);
        coinLB.setBounds(1080, 10, 60, 50);

        nextBT.setBackground(new java.awt.Color(242, 242, 242));
        nextBT.setFont(new java.awt.Font("Bodoni MT", 1, 18)); // NOI18N
        nextBT.setText("Next>");
        nextBT.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 4, 5, new java.awt.Color(174, 0, 0)));
        nextBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nextBTMouseClicked(evt);
            }
        });
        jPanel1.add(nextBT);
        nextBT.setBounds(980, 1210, 100, 40);

        inst_2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/Instruct_2.png"))); // NOI18N
        jPanel1.add(inst_2);
        inst_2.setBounds(0, 570, 1200, 700);

        inst_1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ophelia_net/Instruct_1.png"))); // NOI18N
        jPanel1.add(inst_1);
        inst_1.setBounds(0, 0, 1200, 591);

        jScrollPane1.setViewportView(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 700, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void backBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backBTMouseClicked
        // TODO add your handling code here:
        cd.show(mainPanel, "informationRicko");
    }//GEN-LAST:event_backBTMouseClicked

    private void nextBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nextBTMouseClicked
        // TODO add your handling code here:
        cd.show(mainPanel, "testbg");
    }//GEN-LAST:event_nextBTMouseClicked

    private void backBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_backBTActionPerformed

    private void toolLBMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_toolLBMouseClicked
        // TODO add your handling code here:
        P_Hint_page.backPage=ADDRESS;
        cd.show(mainPanel,"toolPage");
    }//GEN-LAST:event_toolLBMouseClicked

    private void fileLB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fileLB1MouseClicked
        // TODO add your handling code here:
        P_Menu_icon.backPage=ADDRESS;
        cd.show(mainPanel,"menuBtn");
    }//GEN-LAST:event_fileLB1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBT;
    static javax.swing.JLabel coin;
    private javax.swing.JLabel coinLB;
    private javax.swing.JLabel fileLB1;
    private javax.swing.JLabel inst_1;
    private javax.swing.JLabel inst_2;
    private javax.swing.JLabel jLabel_coin;
    private javax.swing.JLabel jLabel_file;
    private javax.swing.JLabel jLabel_tool;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextBT;
    private javax.swing.JLabel toolLB;
    // End of variables declaration//GEN-END:variables
}
